# Generated by Django 4.2.4 on 2023-12-17 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('IdAuto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=10)),
                ('Modelo', models.CharField(max_length=10)),
                ('Patente', models.CharField(max_length=10)),
                ('Vin', models.CharField(max_length=25)),
                ('IdUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('EstadoReservaId', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('EstadoReservaNombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('IdSucursal', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('NombreSucursal', models.CharField(max_length=50)),
                ('TarifaSucursal', models.IntegerField(default=0)),
                ('Direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdTarjeta', models.CharField(max_length=20)),
                ('NumeroTarjeta', models.CharField(max_length=20)),
                ('Nombre', models.CharField(default='0', max_length=50)),
                ('FechaVencimiento', models.CharField(max_length=5)),
                ('CVV', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('iduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('IdReserva', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('CodigoReserva', models.CharField(max_length=20)),
                ('FechaReserva', models.DateTimeField(auto_now_add=True)),
                ('FechaLlegada', models.DateTimeField()),
                ('FechaSalida', models.DateTimeField()),
                ('LugarReserva', models.CharField(max_length=15)),
                ('Costo', models.CharField(max_length=10)),
                ('Penalizacion', models.BooleanField(default=False)),
                ('qrreserva', models.ImageField(blank=True, upload_to='static/images')),
                ('EstadoReservaId', models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='Reserva.estadoreserva')),
                ('IdAuto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Reserva.auto')),
                ('IdSucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Reserva.sucursal')),
                ('IdTarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Reserva.tarjeta')),
                ('iduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('idextenuser', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Telefono', models.CharField(max_length=12)),
                ('Fecha_Nacimiento', models.DateField(blank=True, null=True)),
                ('imageprofile', models.ImageField(default='App/perfil/profile_base.jpg', upload_to='images')),
                ('accesibility', models.BooleanField()),
                ('iduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
