# Generated by Django 4.2.4 on 2023-12-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
