# Generated by Django 5.1.1 on 2024-09-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0002_auto_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='CostoReserva',
            field=models.IntegerField(default=0),
        ),
    ]
